"""empty message

Revision ID: 386161cb6aef
Revises: 620a5757a9e0
Create Date: 2020-10-11 12:23:01.816262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386161cb6aef'
down_revision = '620a5757a9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    # ### end Alembic commands ###
